name: ✨ Plugin Feature Request
description: Suggest a new feature for a plugin
title: "[PLUGIN FEATURE] "
labels: ["plugin", "enhancement"]

body:
  - type: input
    id: plugin_name
    attributes:
      label: Plugin Name
      placeholder: my-plugin
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      placeholder: What limitation are you facing?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      placeholder: What would you like to see?

  - type: textarea
    id: example
    attributes:
      label: Example Usage
      placeholder: |
        jdx-plugins my-plugin build