name: ⚠️ Deprecate Plugin
description: Request to mark a plugin as deprecated
title: "[DEPRECATE] "
labels: ["plugin", "deprecation"]

body:
  - type: input
    id: plugin_name
    attributes:
      label: Plugin Name
      placeholder: old-plugin
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Reason for Deprecation
      placeholder: Why should this plugin be deprecated?
    validations:
      required: true

  - type: input
    id: replacement
    attributes:
      label: Replacement Plugin (if any)
      placeholder: new-plugin

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes